# ========== mode ==========
app.fileMode=true

# ========== local node ==========
app.local.host=154.92.22.203
app.local.port=18888

# ========== file mode ==========
app.input.nodesFile=tron_public_online_nodes_test.csv
app.output.resultFile=connect_result.txt
app.connectTimeoutMillis=5000

# 成功建立连接后保持多久再关闭
# 0 表示成功后立即关闭
# 想观察同时维持多个连接，可以设成 2000 或 5000
app.successHoldMillis=2000

# ========== thread pool ==========
app.threadPool.coreSize=20
app.threadPool.maxSize=50
app.threadPool.queueCapacity=1000

# ========== db mode only ==========
# 只有 app.fileMode=false 才会用到
app.batchInsertIntervalSeconds=10
db.url=jdbc:mysql://187.124.231.27:3306/tron?connectTimeout=5000
db.user=tron
db.password=Wcf314159
db.statusTableName=status
db.onlineTableName=public_online_nodes_test
db.batchSize=50
db.emptyBatchSleepMillis=10000