# ========== app ==========
app.local.host=10.21.213.106
app.local.port=30309

app.batchInsertIntervalSeconds=15

app.threadPool.coreSize=5
app.threadPool.maxSize=5
app.threadPool.queueCapacity=10

# ========== db ==========
db.url=jdbc:mysql://127.0.0.1:3306/tron?connectTimeout=5000
db.user=tron
db.password=change_me

db.statusTableName=status
db.onlineTableName=public_online_nodes

db.batchSize=50
db.emptyBatchSleepMillis=10000
#=============app=================
app.input.nodesFile=nodes.txt
app.output.resultFile=connect_result.txt

app.threadPool.coreSize=20
app.threadPool.maxSize=50
app.threadPool.queueCapacity=1000
app.connectTimeoutMillis=5000